package org.jboss.sepro.service.ws.skeleton;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;

/**
 * This class was generated by Apache CXF 2.6.8.redhat-7
 * 2014-06-24T17:23:56.175+02:00
 * Generated source version: 2.6.8.redhat-7
 * 
 */
@WebService(targetNamespace = "http://sepro.jboss.org", name = "AsyncEcho")
@XmlSeeAlso({ObjectFactory.class})
public interface AsyncEcho {

    @Oneway
    @Action(input = "http://sepro.jboss.org/AsyncEcho/callbackAsyncPingRequest")
    @RequestWrapper(localName = "callbackAsyncPing", targetNamespace = "http://sepro.jboss.org", className = "org.jboss.sepro.service.ws.skeleton.CallbackAsyncPing")
    @WebMethod
    public void callbackAsyncPing(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @Oneway
    @Action(input = "http://sepro.jboss.org/AsyncEcho/pingRequest")
    @RequestWrapper(localName = "ping", targetNamespace = "http://sepro.jboss.org", className = "org.jboss.sepro.service.ws.skeleton.Ping")
    @WebMethod
    public void ping();
}
