package org.jboss.sepro.service.ws.skeleton;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.8.redhat-7
 * 2014-06-24T17:23:56.207+02:00
 * Generated source version: 2.6.8.redhat-7
 * 
 */
@WebServiceClient(name = "AsyncEchoService", 
                  wsdlLocation = "file:/home/ibek/work/github/sepro/web/src/main/resources/wsdl/AsyncEchoService.wsdl",
                  targetNamespace = "http://sepro.jboss.org") 
public class AsyncEchoService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://sepro.jboss.org", "AsyncEchoService");
    public final static QName AsyncEchoPort = new QName("http://sepro.jboss.org", "AsyncEchoPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/ibek/work/github/sepro/web/src/main/resources/wsdl/AsyncEchoService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AsyncEchoService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/ibek/work/github/sepro/web/src/main/resources/wsdl/AsyncEchoService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AsyncEchoService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AsyncEchoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AsyncEchoService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns AsyncEcho
     */
    @WebEndpoint(name = "AsyncEchoPort")
    public AsyncEcho getAsyncEchoPort() {
        return super.getPort(AsyncEchoPort, AsyncEcho.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AsyncEcho
     */
    @WebEndpoint(name = "AsyncEchoPort")
    public AsyncEcho getAsyncEchoPort(WebServiceFeature... features) {
        return super.getPort(AsyncEchoPort, AsyncEcho.class, features);
    }

}
